```{r config, child="section_config.Rmd", message=FALSE, warning=FALSE, echo=FALSE}
```

```{r custom, echo=FALSE}
var_code <- "e_WorldOrder"
var_prettynom <- "World Order"
var_sides <- 5
var_cciso <- "NZL"
var_highlight <- "New Zealand"
```

# `r var_prettynom` - Aggregate Score

**Neighbouring Countries**:

```{r ranking, child="section_rank.Rmd", echo=FALSE}
```

`r neighbours`


```{r maingraph, child="section_maingraph.Rmd", dpi=270, width=7, height=5, echo=FALSE}
```

**My Interpretation and Opinions**:

The World Order aggregate category is sensitive to GDP per capita, as no poor country is among the best ranked countries.

New Zealand's place is a bit under where it could be given the trend of the data, though relatively high overall.

```{r child="section_config.Rmd", eval=TRUE, echo=TRUE, results = "hide", fig.keep="none"}
```

```{r custom, eval=FALSE, echo=TRUE}
```

```{r child="section_rank.Rmd", eval=TRUE, echo=TRUE, results = "hide", fig.keep="none"}
```

```{r child="section_maingraph.Rmd", eval=TRUE, echo=TRUE, results = "hide", fig.keep="none"}
```
