```{r config, child="section_config.Rmd", message=FALSE, warning=FALSE, echo=FALSE}
```

```{r custom, echo=FALSE}
var_code <- "f_PlanetClimate"
var_prettynom <- "Planet & Climate"
var_sides <- 5
var_cciso <- "NZL"
var_highlight <- "New Zealand"
```

# `r var_prettynom` - Aggregate Score

**Neighbouring Countries**:

```{r ranking, child="section_rank.Rmd", echo=FALSE}
```

`r neighbours`


```{r maingraph, child="section_maingraph.Rmd", dpi=270, width=7, height=5, echo=FALSE}
```

**My Interpretation and Opinions**:

Planet an Climate, as is common among aggregate categories, is sensitive to GDP per Capita.

New Zealand has a good overall rank, but a poor rank for a country of our wealth.

```{r child="section_config.Rmd", eval=TRUE, echo=TRUE, results = "hide", fig.keep="none"}
```

```{r custom, eval=FALSE, echo=TRUE}
```

```{r child="section_rank.Rmd", eval=TRUE, echo=TRUE, results = "hide", fig.keep="none"}
```

```{r child="section_maingraph.Rmd", eval=TRUE, echo=TRUE, results = "hide", fig.keep="none"}
```
