```{r config, child="section_config.Rmd", message=FALSE, warning=FALSE, echo=FALSE}
```

```{r custom, echo=FALSE}
var_code <- "g_ProsperityEquality"
var_prettynom <- "Prosperity & Equality"
var_sides <- 5
var_cciso <- "NZL"
var_highlight <- "New Zealand"
```

# `r var_prettynom` - Aggregate Score

**Neighbouring Countries**:

```{r ranking, child="section_rank.Rmd", echo=FALSE}
```

`r neighbours`


```{r maingraph, child="section_maingraph.Rmd", dpi=270, width=7, height=5, echo=FALSE}
```

**My Interpretation and Opinions**:

The Prosperity and Equality aggregate is mildly related to GDP per capita, as wealthier countries are concentrated in the best half of ranks. Given the category, I was expecting the relationship to be stronger.

```{r child="section_config.Rmd", eval=TRUE, echo=TRUE, results = "hide", fig.keep="none"}
```

```{r custom, eval=FALSE, echo=TRUE}
```

```{r child="section_rank.Rmd", eval=TRUE, echo=TRUE, results = "hide", fig.keep="none"}
```

```{r child="section_maingraph.Rmd", eval=TRUE, echo=TRUE, results = "hide", fig.keep="none"}
```
