# R information and citations

This analysis used R 3.3.2

  R Core Team (2016). R: A language and environment
  for statistical computing. R Foundation for
  Statistical Computing, Vienna, Austria. URL
  https://www.R-project.org/.
  
and the packages:

**readxl**

To read in excel files

  Hadley Wickham and Jennifer Bryan (2017). readxl:
  Read Excel Files. R package version 1.0.0.
  https://CRAN.R-project.org/package=readxl

**jsonlite**

To work with JSON data from the Good Country Index website

  Jeroen Ooms (2014). The jsonlite Package: A
  Practical and Consistent Mapping Between JSON Data
  and R Objects. arXiv:1403.2805 [stat.CO] URL
  https://arxiv.org/abs/1403.2805.

**dplyr**

To manipulate data

  Hadley Wickham, Romain Francois, Lionel Henry and
  Kirill Müller (2017). dplyr: A Grammar of Data
  Manipulation. R package version 0.7.4.
  https://CRAN.R-project.org/package=dplyr

**tidyr**

To improve the arrangement of data

  Hadley Wickham (2017). tidyr: Easily Tidy Data with
  'spread()' and 'gather()' Functions. R package
  version 0.6.3.
  https://CRAN.R-project.org/package=tidyr

**countrycode**

To check country identification codes:

  Vincent Arel-Bundock (2017). countrycode: Convert
  Country Names and Country Codes. R package version
  0.19.
  https://CRAN.R-project.org/package=countrycode

**rvest**

To gather data from web pages

  Hadley Wickham (2016). rvest: Easily Harvest
  (Scrape) Web Pages. R package version 0.3.2.
  https://CRAN.R-project.org/package=rvest

**feather**

To create intermediate files

  Hadley Wickham (2016). feather: R Bindings to the
  Feather 'API'. R package version 0.3.1.
  https://CRAN.R-project.org/package=feather


**knitr**

To create finished reports

  Yihui Xie (2017). knitr: A General-Purpose Package
  for Dynamic Report Generation in R. R package
  version 1.16.

**ggplot2**

To make plots of the data

  H. Wickham. ggplot2: Elegant Graphics for Data
  Analysis. Springer-Verlag New York, 2009.

**viridis**

To automatically produce a nice colour scheme for the plots

  Simon Garnier (2016). viridis: Default Color Maps
  from 'matplotlib'. R package version 0.3.4.
  https://CRAN.R-project.org/package=viridis

**bookdown**

To produce the finished website and pdf

  Yihui Xie (2017). bookdown: Authoring Books and
  Technical Documents with R Markdown. Chapman and
  Hall/CRC. ISBN 978-1138700109

